version: '3.8'

services:
  portfolio-nuxt:
    container_name: portfolio-nuxt
    build:
      context: .
      dockerfile: Dockerfile
    image: portfolio/frontend:dev
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=development
    command: npm run dev:docker
    networks:
      - portfolio-network

volumes:
  node_modules:

networks:
  portfolio-network:
